apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 20.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/sonarr
      tag: latest
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: sonarr.${ENV}.example.com
          paths:
            - path: /
              pathType: Prefix
