apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtop
  namespace: desktop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtop
  template:
    metadata:
      annotations:
        desktop.test.tuntelder.com/mobile-profile: "v2"
      labels:
        app: webtop
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: webtop
          image: lscr.io/linuxserver/webtop:ubuntu-kde
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Amsterdam
            - name: TITLE
              value: Tuntelder Desktop
            - name: START_DOCKER
              value: "false"
            - name: PIXELFLUX_WAYLAND
              value: "true"
            - name: SELKIES_SCALING_DPI
              value: "160"
            - name: SELKIES_GAMEPAD_ENABLED
              value: "false|locked"
            - name: SELKIES_SECOND_SCREEN
              value: "false|locked"
            - name: SELKIES_UI_SIDEBAR_SHOW_GAMEPADS
              value: "false|locked"
            - name: SELKIES_UI_SIDEBAR_SHOW_SHARING
              value: "false|locked"
            - name: SELKIES_UI_SIDEBAR_SHOW_STATS
              value: "false|locked"
            - name: SELKIES_UI_SIDEBAR_SHOW_TRACKPAD
              value: "true|locked"
            - name: SELKIES_UI_SIDEBAR_SHOW_KEYBOARD_BUTTON
              value: "true|locked"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 4Gi
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: webtop-config
