apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtop-config
  namespace: desktop
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
