apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 8.6.0
      helm:
        valuesObject:
          credentials:
            useSecret: true
            existingSecret: velero-credentials
          configuration:
            backupStorageLocation:
              - name: default
                provider: aws
                bucket: lab-backups
                config:
                  region: auto
                  s3ForcePathStyle: true
                  s3Url: https://BUCKET_ENDPOINT
            volumeSnapshotLocation:
              - name: default
                provider: aws
          schedules:
            daily:
              schedule: "0 2 * * *"
              template:
                ttl: "168h"
                includedNamespaces:
                  - "*"
          initContainers:
            - name: velero-plugin-for-aws
              image: velero/velero-plugin-for-aws:v1.11.1
              volumeMounts:
                - mountPath: /target
                  name: plugins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
