apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  source:
    repoURL: https://github.com/myrenic/test.git
    targetRevision: HEAD
    path: kubernetes/apps/velero/chart
    plugin:
      name: helm-sops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
