apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: argocd
stringData:
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:EmdVZYYpY/nvdECUi+yFQH3DNl7KrDQRjwDtOSRBVq5BIH8O,iv:0s1FTPY1ZnkP595Nx9xjDUeDfPM2cp6FYTMnf0ekzZo=,tag:RHtBQnOw9/ktzvWkccKHeg==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:2auJQMTJow99uKoGwvJWh6/kXd/Q9eU4Y/CHZHGaViSbK9pe5Y8vpw==,iv:9ZaBi8dP1yAzPXvbv4Pz/qipc/9gyxJpzFie464kKZA=,tag:csTXEkr5+csFMkFeizvKjQ==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:KHLTJGrrpMm0StH1uctC+YjShN8j207pRe5RVKuUQpAtC4ub,iv:LLoB6EiO1NMVzdRObeCMrcGgff5vtxgskT6wF0fMgAY=,tag:e+/AkX30wo7xNHbHbqdDhw==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:014ApkG1bntEyX67NX1pTNddiWtFw4bsbHp9WVDB5X81J+iealITjg==,iv:EJWiAtpOlYfq11vs+CsylRHSmswhSe26dRN1L7ixU38=,tag:VHLt4kVALcRQYbMzYP3+Mg==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:fC/pcF+CDY0D3AnrAYTkMet/2DmagesgwjuO0d5xdrjeFg/Z1vZY2Pj3voo=,iv:XX9+Mu5tEDR8g67GtWzwOxw6T8LkwlBxxZwPs24z6WA=,tag:PI5cNoNbZaW48/2TNEn3vg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:GIIYeEbajSNJ4tqpBm/dPKkkng==,iv:VxJo4cQq89G80oEhxN4tX9yRMjiw8dVEAAPn+1pAQSQ=,tag:dnW0iZCXuAKy0h3kQ+O/5g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:zsXVvlB6kdcl03qzIQ==,iv:4gjNEk/zClJuzzQD3qY4jfzj0fd1MF1z1aFo0whFbDI=,tag:DcLojjaxGj3KE5x5AEnCMg==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUSswTlpSWE40SWN2MHE3
            MkFYMm5vM2xjYlJwcld2UWROK1pJV0U0a1ZzCm1PbGh1bmpmbUtTSXRjOEFFVCtt
            NkFOSFkvck5ZTUFwMWlETUIrcUVjbk0KLS0tIDVOdi9IelNOMU1EVjJsaGo1dmp2
            NWF0NnZWKzE4MlRnNEtjOWdsK0lRbzAKovSsYsHSluas4amFPc+WZc6b1C39NmlB
            REfyWmJSj7exabmvMudc7ju6qxjAeMrCFQwvkh8+ynCpsWGcHhAt4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T12:59:36Z"
    mac: ENC[AES256_GCM,data:wltD3Ix40+WnpQiv7ru04sb8SQRxFbog4SgV3Dktsn9RNQnDKOdeQLJ0VBr15GgjyRdZK9OcMeZgdnHvADs+a7ttbYxQALbxcpPJ7JnAsoZ93DOnSJx5H9yznwJ2GL1ntBWXzY1SKHeyGjNpqm9Ms0oV0/lpeqnvR1WU9VWJXKs=,iv:Um/0lWmWspPfWnhjaWDzMuZh9uFzURawwoqNc+K0ejw=,tag:H2JMYtRYd2eHf0EAZkMVNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
