apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: argocd
stringData:
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:1L6Q3ZSycQmVxKu1rrChWn36D4ELHY34D6m2E7l9hHXGr0SI,iv:/w251fYPEO6r9vUy5NR4jfcBgThDWcZBK8Ss8c9FGDU=,tag:SKShjmKQ0S+2MIM1TUiGTA==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:InwoPGE16MkyJllqlxKlByrsw2f50sdGmtE5ol6LREEyWAcX2Sy9KQ==,iv:prEc2fVDoa7TipI+/WfB95d8fEEE61wYkR7ZXOBF/p8=,tag:q2ZA0UmEl3wSYg5yWYFYJA==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:CN0VLaPZiC+1EgE0qvIdctdG9q5zi+mhRFqzzq7jkj+WLWTs,iv:nDOKenNJhzMoXMpLDnIn7Q1g03RumG/kx1cAtFNCHjs=,tag:b5PqsD0IsAZ4oYvzcp0IKQ==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:FHq1Rh+vPLuTXV9GDEQls02nLPGazPE2/ls/Cm3dlIGzC07g6EOF/g==,iv:/7P5NckQj9Tl35XoganNWkNgvexFIMAfgLjMl3LW/WU=,tag:6Qpcv6bgY94K8PCVyCWgqQ==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:rOOLhOqAPAY2Z/kA6gdIORul/nxMBIjNfXtPBq4EiI3RxvcHC/JdM/RQ8IE=,iv:TGiEAaoyTvsiUznpLJQWw+Y9eSexoUPY1AqCGsXV6iw=,tag:hWREmKrYhlga9NJ8gLtkcg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:wxiB2jmuS3OIfO7kAfaHSpx9wA==,iv://xS5ey5i7gvA3sC5IotHO+cny8oypyGGgKDXaw9LJg=,tag:UGEdWcPkON786MCKM6AXuQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:NRxkHZ1kRFdYDjluJCgyyPzK,iv:XGiK54Hi/9+Wx42Fcz+Yv+WNIHP5P2K7BcZxz/5U0ek=,tag:ze3DgprYVbFn7U5OaJ5VWw==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMm1LK3VBK2Y2UDFXaDFK
            QVVoQWNxWnF0SHRMM1c3RURSUTFmNmRIZTNJCm05NkdJck16enIrWjRyamNPZEJF
            V2xCVlV4a1REWG5meW9JaFNvTVFWSW8KLS0tIFk0UUpsRmFnUUMvNmplNFVtcDUx
            ODRKR0hmZm81eFR3Uk5ZTmV2c0ZvczgKEEaNg/RI6USmnEJPv/jBPcKkczJqV77i
            fXlGmgBhwbjtyxlemVWRY3TwGU3elbDXLFo63552I1unymhFWr1iXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T15:37:13Z"
    mac: ENC[AES256_GCM,data:ZW8CKy24gQyleqB2EELIWF7UZ4VZglNB+aDRZ1bnfIOS2CONbgWvsx8aPKab3OStcgRbamlix/RFInS4VfEGAgk6m1/J5B8H4MsC1KMqiE3CN1ddlQiR7GOfp7oUeKP62b7CO1LI9VFfnHFPlNls2VO16EbBRuXl5EdF9OTK1N0=,iv:j5Th3K2/xllVKS1z4s4SjKtmYp9lUWvqO38hO1OPDA8=,tag:NgdzIUKX6MYs5/oQ0QGlrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
