apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: argocd
stringData:
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:PfI5ngUEFPEp+Va/zopqMirvI+wt+e5p2qq7A2CtqXlp39aU,iv:ENRGpUtWQ2Nw6C7k5FHq3kIInesFNqbouOQt9XnUyl8=,tag:2uEQ1HYmVDEB3c8i5g47yw==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:npCtj04McHZcXRFwvvldmiSvvmMRocHuqx/kxzzOcKQ0MSqowZm9Og==,iv:qjbCEhQNPxozQ9JZ8EImKwSWwt+HmTBae8sj5jE0oEM=,tag:6d8+y8L7ZezWITfQfldJHQ==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:n4GBH/iiAKhSvRHMoGDH6ah/3TZzgr0RF2cjAAy5muYETHZA,iv:cRjmxMn42IJB3na0OiqUh+0JnTRYAKTbMnfIWsTiQGY=,tag:VAWXex0GVX1KelE7nBcL8g==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:IP+YS58bZ3L5em+APXTAtdi+69TEYJLSIMJOsbVguZpy1NViCSGi/w==,iv:jZLuqmFyDz42kIstIwSeYU2/vd7IBFVvDETndCvXrP0=,tag:LjiajFwCU7bYFoKvz2bssA==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:hKuwfBooerq2+aTtiA7/fRv7zra1cBzH/12onBw4LWr3E3VoJjYnRxZNoKs=,iv:ZtB/D1rixHGE+G02gH5uEJfi98k4NnxfJfUyxWgSX8A=,tag:jYamf0FY/B8plkXpmL7q6w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ezTHrjiO58XEVkNJq/sSn3DFDw==,iv:+BWuhgH9JPx4tOY6PAmh2toCOPDQapEXfGP6TqPbQR8=,tag:UPe14ZErz3XKjSnoNhYfFQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:YioLFTLifbIRTdNqZKuhWJ3P,iv:p3mrovxMlW08eCUCu9Cq63h4suk9MuhC0bH/4OvGftE=,tag:K/wsHbbSfJSet6jm0tjkiw==,type:str]
    TAILSCALE_AUTHKEY: ENC[AES256_GCM,data:HTiqabNzfcSHWMbFTWZtkvLU3UflxHmU5UdiefTTdKuG4ApCMSxOoFMPM2sObCypi9PU/lHmY/RyQorBdQ==,iv:W1p0WCIoe/Y8pdTJDxktxLE9RjdHKq0q5i9hXsQK7ME=,tag:lXGqXIrIo4g+aeH/noWGYA==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb0NBWEhvOXVEN1Uzdlps
            N3ZaQm11a3NTUVViaGRSQUI3QUFzU1hNSzM4Clg3ejE2RzVoLzlFdGU5R0U1WkFU
            L2ZTc0YwQnM4SXk5cVVaeDFOZGV1MjgKLS0tIEJPbjZHZTBYcDU0QkRHa0FaY3Ny
            REZIOGx0YkZzSGc4cDVWUDFORlZRbEUKf/P/o6gVC4uUHnSgjRoFyzczFNPEwFbg
            eaiLnoQF23U8/qa1Awtdce4/ZIhVEiVkIPe1UnGF77GPZGJXeNJn2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T16:25:40Z"
    mac: ENC[AES256_GCM,data:0Xq230sCngG/MgZ8gTD4wpQhj2bH5g2+2EP3gsQlKGDDXRQZPxgdWJZBA3RuFaOaNzwz7xRpUFm5JRzLol7UNla/0Y9jB6znYA6sIphpGzum4ycJMjEusjYn1ceX6rk6/5edMXHCXiCYKiyKKUT5BOA3t2L9D6/n/6Y0QbF9D1Q=,iv:ng/nQzZ1gO4+ehlWSW45rPi9rlD/S+k9czjrXBwMsZQ=,tag:mvTEj4RRx0F/ATaRXh1PYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
