apiVersion: v1
kind: Secret
metadata:
    name: github-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:WIjHVjuksg==,iv:Q22gMdcL198lbeOLW+sZIbUkuyYxJHl5jRKOAxIZ8Ac=,tag:0+vVGM0HGod6cu/VOtU51Q==,type:str]
    password: ENC[AES256_GCM,data:9qWsedJz+Hh4OY6eI63N9cnQFuY9VaLoqTz8iXRPq+MCOzU5AFoNxg==,iv:pxItZaje7Dh46L0idRgHeS4hoPqNzayOozcZiDduHlE=,tag:+7C0jOlBKGZ8WgfD0yftHw==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZVpYQVdNcmovV2Z2WlFh
            VUFCWjh0ZFU2RkVTOFFDVVg0czJkcEEzeng4CitWZ0xLbTlWZnlsSGFjN2pxcy9F
            L0NuUGlQNmJGbVIwL0RMZDFkSnRDRUEKLS0tIFdDUjNyZnpUaVEwVlgybEVUQUlq
            SlpvTGFUMnFKQjFwb2FoWXNKYzVjUHcK2eIZYU6PsApd+CWkGv0yHVeZagNfiCW5
            KdskgkGHO8xYUQPpytH2TWOicWWoD5kNS3n+AP2rCewWlAGkVisW8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T19:57:37Z"
    mac: ENC[AES256_GCM,data:HbnoOQGrRSRPSqKumtIdUYw+Pu6GjKPCc5nlSXTtDA0ycXbHAXckdjpFhKi7aTMf5/opkCSRtIV8TEvqOJaF0l7aSyGZkbbkXj3k9uDUtMPHxAilM3JJTnvpmUmGrSnQmCI+KJodryQ4p7iJE0YU5VGzQIZg3tNed7xCQcLRGQU=,iv:XQ0KFNTMk25+dA1jSJv/KnflEPz2Otgl1ZvOZ/UKFrM=,tag:dSn2URK7odbdR4n/XJw4IQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
