apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.15.3
      helm:
        valuesObject:
          speaker:
            ignoreExcludeLB: true
    - repoURL: https://github.com/myrenic/test.git
      targetRevision: HEAD
      path: kubernetes/apps/metallb
      directory:
        include: '{namespace.yaml,pool.yaml}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
