apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.3.70-10.0.3.73
    - 10.0.3.75-10.0.3.75
    - 10.0.3.77-10.0.3.79
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lan-pool
  namespace: metallb-system
spec:
  ipAddressPools:
    - lan-pool
