apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://github.com/myrenic/test.git
    targetRevision: HEAD
    path: kubernetes/apps/cilium/chart
    plugin:
      name: helm-sops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
