apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-tls
  namespace: traefik
spec:
  secretName: domain-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - "*.test.tuntelder.com"
    - "test.tuntelder.com"
