apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab-ca
  namespace: lab-ca
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: ca.lab.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lab-ca
                port:
                  name: http
