apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lab-ca
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: lab-ca-files
    files:
      - index.html
      - lab-cluster-ca.crt
