apiVersion: v1
kind: Secret
metadata:
    name: netbird-api
    namespace: netbird
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:jdGSSv1MMa5jr2pjQVfV15yn1QAmx7+vJcdteFo/OT5u7vskz41EmA==,iv:sUwBQ7DydRaPV77UnwgjkrFXxiVG/MYjyiSQv4EQ+CY=,tag:AEriiLYljpdSC0iCKBREfQ==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLU20xdi9YOHFKZExMaU9s
            aGMzTnk2YjJ3NXpQSG5MRjliMXk5alE2cFNFCmVqNFNTY2NpT3hVOEhHTnAxWTNt
            UTU3R3AwNitmUDRTWitPU1RlajI0elEKLS0tIDF3UXliUnRwUThwM2ljc2dPZVFC
            cHRGNEpQVEV0K3NiUHFjKzh2R0J1ekUKABipD6fpu2KNRUhem85fJytTgu7jE5Rq
            DkYnUK6IqcXmLTwkjXi+0FthudQ84nPVws03Ojcl1x3Q6q7tRWKHiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T03:45:27Z"
    mac: ENC[AES256_GCM,data:BJaPDFttIjeA8lZktXFTNmhNgeVd1FcmGyuJEKEhOINafclsJjI0kxbIBmFGmH4pn95KP+JH68fi9QZdDWiB7bIgXJGtVW84EIqpAYzBC4JdIRhhBnrpvK+PBjqEAvRyVeT46IC4ktlb8v+VvXo0ldW6+KL+rW92xtPBWR2AJQw=,iv:aUoaUNlNr9XIW6tyFDO3R64SwV1vtrhfYKbb0L6uVIU=,tag:9x2qL1mSmXZFEeGFTu0owQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
