apiVersion: v1
kind: Secret
metadata:
    name: netbird-setup-key
    namespace: netbird
type: Opaque
stringData:
    setup-key: ENC[AES256_GCM,data:LWVdV5rmHMAiswi1HGJOw4rqj31vdOowh0CeQRRBPMEjIq41,iv:Lc30jbSG+Nplu7Rfnuxp7HPVm/yb0PNiGrQyONWioAA=,tag:GVjn2yrOPjW9HRx1zmShcA==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeURtcDZxUXM1cjFsbVBC
            Witna2lObmoxRnNaS1lFaklkSzNSUVAxTDBRCkRLbkh3VGdZNS84SUZqYVZzd2xa
            RnRmWXRvWUxRK2FuVHdBRG5ERDB2MU0KLS0tIGh0TW9wOElHRm9jRDNmTmhsQUlZ
            Zjd1QnJmZGJqSlYrZFVxbWoxL3MxYzQKQuuM9u8aumI6eYpgk3ALjxn+iXt83FAl
            4XnR6xoRd6aUv1izEEAPZ5mgipUnGanCEj8/5VL+ZpO47ISEsaBnRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T19:57:37Z"
    mac: ENC[AES256_GCM,data:pvM6tscyyDEo9YNKXtXQmixLLyVW3Gqekq7oe0GnOk6Kmdh7V2bsoKe2DNNv9fq2OkkZ7yLLFMWDq2ivQII5jiUlOS4CZrjsrf0cOyLox2YlxVStwkJkS8LfwcOSdMy60dZAHZyjPPAtMFSBcdl/L/kY5OstwJLgvWN9ZKhZyIo=,iv:9cwzgtNHVUMqhb5ahH8XRek0cb9+NKYL69rREw6KZ1Y=,tag:xH1nPItek7mIyixQVNdNmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
